apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatroom-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatroom-backend
  template:
    metadata:
      labels:
        app: chatroom-backend
    spec:
      containers:
      - name: chatroom-backend
        image: ojasvisharma111/chatroom-backend:latest
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
        ports:
        - containerPort: 8080
