apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatroom-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatroom-ui
  template:
    metadata:
      labels:
        app: chatroom-ui
    spec:
      containers:
      - name: chatroom-ui
        image: ojasvisharma111/chatroom-ui:latest
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
        ports:
        - containerPort: 80
